### ISSUE TITLE
Random exception

### ISSUE THREAD

**Issue by AmauryCarrade** [zDevelopers/BelovedBlocks#16]
This spawned on my console. Maybe zLib related.

```
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
        at eu.carrade.amaury.BelovedBlocks.zlib.components.attributes.Attributes.indexOf(Attributes.java:277) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.zlib.components.attributes.Attributes.find(Attributes.java:314) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.zlib.components.attributes.Attributes.get(Attributes.java:465) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.BelovedItem$Attribute.fromItem(BelovedItem.java:63) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.BelovedItemsManager.getFromItem(BelovedItemsManager.java:106) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.tools.ToolsManager.use(ToolsManager.java:63) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.listeners.BlocksListener.onPlayerInteract(BlocksListener.java:61) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        ... 17 more
```

**Comment by prokopyl** [comment]
This should be fixed with the latest zLib revision, can you confirm ?

**Comment by AmauryCarrade** [comment]
I can in two hours

**Comment by prokopyl** [comment]
This should be fixed now.
