### ISSUE TITLE
1.11 compatibility

### ISSUE THREAD

**Issue by AmauryCarrade** [zDevelopers/BelovedBlocks#19]
Got this error:
```
java.lang.NoSuchMethodError: org.bukkit.DyeColor.getData()B
        at eu.carrade.amaury.BelovedBlocks.blocks.portals.NetherPortalBlock.getItemBuilder(NetherPortalBlock.java:42) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.BelovedItem.makeItem(BelovedItem.java:149) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.blocks.portals.NetherPortalBlock.getCraftingRecipes(NetherPortalBlock.java:48) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.BelovedItemsManager.register(BelovedItemsManager.java:43) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.blocks.BelovedBlocksManager.register(BelovedBlocksManager.java:59) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.blocks.BelovedBlocksManager.onEnable(BelovedBlocksManager.java:49) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.zlib.core.ZLibComponent.setEnabled(ZLibComponent.java:68) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.zlib.core.ZLib.loadComponent(ZLib.java:98) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.zlib.core.ZLib.loadComponent(ZLib.java:120) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.zlib.core.ZPlugin.loadComponent(ZPlugin.java:76) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.BelovedBlocks.onEnable(BelovedBlocks.java:58) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_111]
```

**Comment by AmauryCarrade** [comment]
Also:
```
[20:49:15 ERROR]: Could not pass event BlockPlaceEvent to BelovedBlocks v1.2-dev
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:146) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at net.minecraft.server.v1_11_R1.ItemStack.placeItem(ItemStack.java:186) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:490) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:897) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_111]
Caused by: java.lang.NullPointerException
        at eu.carrade.amaury.BelovedBlocks.listeners.BlocksListener.onBlockPlace(BlocksListener.java:74) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_111]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-16c940b-691628a]
        ... 18 more
```
