### ISSUE TITLE
Error 1.11

### ISSUE THREAD

**Issue by Max633** [zDevelopers/BelovedBlocks#21]
Hi

```
[22:02:34 ERROR]: Error occurred while enabling BelovedBlocks v1.2.1 (Is it up to date?)
java.lang.IllegalStateException: Configuration is not loaded.
        at eu.carrade.amaury.BelovedBlocks.zlib.components.configuration.ConfigurationItem.getInstance(ConfigurationItem.java:228) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.zlib.components.configuration.ConfigurationItem.getConfig(ConfigurationItem.java:239) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.zlib.components.configuration.ConfigurationItem.getRawValue(ConfigurationItem.java:244) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.zlib.components.configuration.ConfigurationItem.get(ConfigurationItem.java:85) ~[?:?]
        at eu.carrade.amaury.BelovedBlocks.BelovedBlocks.onEnable(BelovedBlocks.java:54) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at me.jmgr2007.Reloader.Utils.load(Utils.java:149) [Reloader.jar:?]
        at me.jmgr2007.Reloader.ReloaderListener.onCommand(ReloaderListener.java:113) [Reloader.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:636) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

Thank :)

**Comment by prokopyl** [comment]
Hello,
Can you give a bit more information on what you were doing and what plugins were in use whan this happened ? Giving just a stack trace isn't enough.

**Comment by Max633** [comment]
Hi, my problem is solved

**Comment by Max633** [comment]
But : 
    others:
        burning_furnace:
            name: "Indefinitely Burning Furnace"
            craftable: true   # Crafted with a furnace and a blaze powder (shapeless recipe)
            itemGlow: true

not work^^"

**Comment by AmauryCarrade** [comment]
This item was removed from the plugin because it does not works well (mainly world updates problems).
