### ISSUE TITLE
1.12 Compatibility Question

### ISSUE THREAD

**Issue by StarBound6494** [zDevelopers/BelovedBlocks#22]
Hello,
My server has updated to 1.12 and while ingame the plugin works perfectly. the console is flooded with: Unable to pass itemCraftEvent errors. Is this something that I can fix myself? Or is this something that can only be fixed with an updated plugin. If so, are there any plans to update? 

Thank you.

**Comment by prokopyl** [comment]
These errors usually come from the plugin itself, not from your configuration, so an update will be required.

Can you give us the full error log, so we can debug and fix it ?

**Comment by AmauryCarrade** [comment]
I caught one:

```
[16:02:48 ERROR]: Could not pass event PrepareItemCraftEvent to BelovedBlocks v1.2.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:772) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.Container.a(Container.java:641) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.ContainerPlayer.a(ContainerPlayer.java:75) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.InventoryCrafting.setItem(InventoryCrafting.java:130) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.Slot.set(SourceFile:79) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.Container.setItem(Container.java:456) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2058) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at eu.carrade.amaury.BelovedBlocks.listeners.CraftingListener.onPreCraft(CraftingListener.java:84) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        ... 21 more
```

**Comment by AmauryCarrade** [comment]
Now fixed. Sorry for the delay… :/
